processor: src.icij_processor
sources:
  - table: nodes_entities
    path: data/nodes-entities.csv
    node_type: entity
    id_field: node_id
  - table: nodes_addresses
    path: data/nodes-addresses.csv
    node_type: address
    id_field: node_id
  - table: nodes_intermediaries
    path: data/nodes-intermediaries.csv
    node_type: intermediary
    id_field: node_id
  - table: nodes_officers
    path: data/nodes-officers.csv
    node_type: officer
    id_field: node_id
  - table: relationships
    path: data/relationships.csv
